FBEditableTweakDateViewController: Fix broken UIDatePicker.
Lightricks/Tweaks pull request #31
Opened 2021-07-28 11:39 UTC by GalBerezansky

When iOS 14 was introduced the default style of `UIDatePicker` transformed from wheel to
auto - in iOS 14 the auto style worked properly but in iOS 15 the layout
at `FBEditableTweakDateViewController` was broken.

This commit makes sure that the style will be wheel and fixes the
problems raised by the shift to iOS 15.

2021-07-29 12:55 UTC, byohay commented
The wheel is not centralised, see picture below. Can you fix this?
![IMG_C66A6E5BD6C0-1](https://user-images.githubusercontent.com/15332602/127495775-81541c37-d382-43fc-8687-5cc7f779f35e.jpeg)

2021-07-29 14:27 UTC, GalBerezansky commented
On what device did you get this effect? Have not been able to reproduce it with my 11 pro

2021-08-02 14:39 UTC, GalBerezansky commented
Fixed the iPhone11 iOS 15 problem - did F&S.

2021-08-03 07:11 UTC, byohay requested changes

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // Due to a shift with the default value of \c UIDatePickerStyleWheels from iOS 14 and beyond
In the commit you say it's from iOS 15, what is it then?

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // Due to a shift with the default value of \c UIDatePickerStyleWheels from iOS 14 and beyond
Due to change of the default value

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // Due to a shift with the default value of \c UIDatePickerStyleWheels from iOS 14 and beyond
`\c UIDatePickerStyleWheels` -> `\c UIDatePickerStyle`

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +                           constant:40];
indentation. Same for below.

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +- (void)centralizeDatePicker {
centralize is not exact, it's anchored to top-center. IDK if there's a better wording for it though

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // the UIDatePicker is no longer Wheel style automatically thus this code is needed.
`thus this code is needed` -> This is redundant IMO

2021-08-03 07:11 UTC, byohay commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // Due to a shift with the default value of \c UIDatePickerStyleWheels from iOS 14 and beyond
and beyond -> and above

2021-08-03 12:43 UTC, GalBerezansky commented on FBTweak/_FBEditableTweakDateViewController.mm
> +    // Due to a shift with the default value of \c UIDatePickerStyleWheels from iOS 14 and beyond
But I did elaborate on the differences between the effect in iOS14 and iOS15.

2021-08-03 12:46 UTC, GalBerezansky commented on FBTweak/_FBEditableTweakDateViewController.mm
> +- (void)centralizeDatePicker {
maybe `makeDatePickerConstraints` which resembles the common use with masonry?

2021-08-03 13:19 UTC, byohay approved these changes

2021-08-03 13:19 UTC, merged